DROP TABLE IF EXISTS genie;
DROP TABLE IF EXISTS melon;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE genie (
  name VARCHAR(80) NOT NULL,
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(250), 
  singer VARCHAR(8), 
  Frequency INTEGER,
  user_id INTEGER,
  FOREIGN KEY(user_id) REFERENCES user(id)
);

CREATE TABLE melon (
  name VARCHAR(80) NOT NULL,
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(250), 
  singer VARCHAR(8), 
  user_id INTEGER,
  FOREIGN KEY(user_id) REFERENCES user(id)
);